language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

  # Install phantomJs.
  - sudo apt-get update
  - sudo apt-get install build-essential chrpath libssl-dev libxft-dev
  - sudo apt-get install libfreetype6 libfreetype6-dev
  - sudo apt-get install libfontconfig1 libfontconfig1-dev
  - export PHANTOM_JS="phantomjs-1.9.7-linux-x86_64"
  - wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
  - sudo mv $PHANTOM_JS.tar.bz2 /usr/local/share/
  - sudo tar xvjf /usr/local/share/$PHANTOM_JS.tar.bz2
  - sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/share/phantomjs
  - sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin/phantomjs
  - sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/bin/phantomjs

  # Install grunt.
  - npm install -g grunt-cli
  - npm install -g bower


install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

  # install drush
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*@dev
  - phpenv rehash

before_script:
  # Install Solr
  - cd $TRAVIS_BUILD_DIR
  - drush dl search_api_solr
  - curl -sSL https://raw.githubusercontent.com/zero2one/travis-solr/master/travis-solr.sh | SOLR_CORE=capacity4more SOLR_CONFS="$TRAVIS_BUILD_DIR/search_api_solr/solr-conf/4.x" bash
  - rm -R $TRAVIS_BUILD_DIR/search_api_solr

  # Install Tika
  - mkdir -p $TRAVIS_BUILD_DIR/tika
  - cd $TRAVIS_BUILD_DIR/tika
  - wget http://www.eu.apache.org/dist/tika/tika-app-1.6.jar
  - chmod +x ./tika-app-1.6.jar
  - cd $TRAVIS_BUILD_DIR

  # Install capacity4more profile.
  - cd $TRAVIS_BUILD_DIR
  - cp $TRAVIS_BUILD_DIR/capacity4more/behat/travis-ci.config.sh config.sh
  - ./install -dy
  - cd $TRAVIS_BUILD_DIR/www
  - drush cc all --yes

  # Create a behat configuration file.
  - cd $TRAVIS_BUILD_DIR/capacity4more/behat
  - cp behat.local.yml.travis behat.local.yml

  # Create Drush alias.
  - cp $TRAVIS_BUILD_DIR/capacity4more/behat/aliases.drushrc.php ~/.drush/
  - composer install --prefer-source

  # Index content in Solr
  - drush @capacity4more search-api-index
  - sleep 10
  - wget http://localhost:8983/solr/capacity4more/update?commit=true

script:
  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  # start a web server on port 8080, run in the background; wait for initialization
  - drush @capacity4more runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

  # Run selenium.
  - cd $TRAVIS_BUILD_DIR/capacity4more/behat
  - wget http://selenium-release.storage.googleapis.com/2.40/selenium-server-standalone-2.40.0.jar
  - java -jar selenium-server-standalone-2.40.0.jar -p 4444 &
  - sleep 5

  # Run phantomJs.
  - phantomjs --webdriver=8643 > ~/phantomjs.log 2>&1 &

  # Run behat tests.
  - cd $TRAVIS_BUILD_DIR/capacity4more/behat
  - ./bin/behat -p phantomjs --tags=~@wip

  # Run WebTests ---------------------------------------------------------------
  - drush @capacity4more -y en simpletest

  # Add the tests here. Use the group name, classname or the file.
  - drush @capacity4more test-run "capacity4more:og:vocab"

  # End Run WebTests -----------------------------------------------------------
