language: php

env:
  - INSTALL_PROFILE=1
    BEHAT_TAG="api"
    CODE_REVIEW=0
    SIMPLETEST=1
  - INSTALL_PROFILE=1
    BEHAT_TAG="javascript"
    CODE_REVIEW=0
    SIMPLETEST=0
  - INSTALL_PROFILE=0
    BEHAT_TAG=
    CODE_REVIEW=1
    SIMPLETEST=0

php:
  - '5.6'

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - date
  - sudo apt-get update > /dev/null
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - date

  # Install some server dependencies.
  - $TRAVIS_BUILD_DIR/ci/bin/install_server.sh

#  # Update node.js to 4.x
#  - $TRAVIS_BUILD_DIR/ci/bin/install_nodejs.sh
#
#  # Install Apache + extra PHP packages.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_apache.sh
#
#  # Install drush.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_drush.sh
#
#  # Install Coder for code standard reviews.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_coder.sh
#
#  # Install MySQL.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_mysql.sh
#
#  # Install Apache Solr, pass the name of the SOLR core.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_solr.sh capacity4more
#
#  # Install Tika, pass the desired version number.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_tika.sh "1.12"
#
#  # Configure Behat + Install dependencies.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_behat.sh
#
#  # Run headless browser environment, only needed for javascript behat tests.
#  - $TRAVIS_BUILD_DIR/ci/bin/install_browser.sh
#
#  # Install grunt & bower
#  - $TRAVIS_BUILD_DIR/ci/bin/install_taskrunners.sh
#
#  # Install capacity4more profile.
#  - travis_wait 35 $TRAVIS_BUILD_DIR/ci/bin/install_drupal.sh

before_script:
  - date

#  # Index content in Solr.
#  - $TRAVIS_BUILD_DIR/ci/bin/index_drupal.sh

script:
  - date

  # Run WebTests
#  - $TRAVIS_BUILD_DIR/ci/bin/run_simpletest.sh

  # Run behat tests, different run based on the environment setting.
#  - $TRAVIS_BUILD_DIR/ci/bin/run_behat.sh

  # Run Code Style validation.
#  - $TRAVIS_BUILD_DIR/ci/bin/run_coder.sh

after_script:
  - date

after_failure:
  # Zip dumps and mail
  - $TRAVIS_BUILD_DIR/ci/bin/report_watchdog.sh

  # Output watchdog entries (errors).
  - $TRAVIS_BUILD_DIR/ci/bin/report_watchdog.sh

notifications:
  slack: amplexor:7ssq8h2xLhkDGyJCw6rtmfOY
